[[pages]]
name = "OPTIONS"
icon = "ğŸ§·"
is_section = true

[[pages]]
path = "Therapist.py"
name = "Thought Therapist ğŸ§‘â€âš•ï¸"

[[pages]]
path = "faq.py"
name = "Frequently Asked Questions â”"

[[pages]]
path = "about.py"
name = "Know more about developer ğŸ§‘â€ğŸ’»"